import type {Academic,DeskState,Lecture} from './domain';
export type Version={version:number;updatedAt:string;lecture:Lecture};
export type StoredLecture={versions:Version[]};
export type StoredFile={noteId:string;name:string;type:string;data:string};
export type Snapshot={schemaVersion:2;notebookId:string;snapshotId:string;publishedAt:string;academic:Academic;state:DeskState;lectures:Record<string,StoredLecture>;annotations:Record<string,{text:string;revision:number}>;files:Record<string,StoredFile>};
export type Overlay={revision:number;completed:Record<string,boolean>;tasks:Record<string,DeskState['tasks'][number]|null>;grades:Record<string,DeskState['grades'][number]|null>;practice:DeskState['practice'];lastRequest?:string;annotations:Snapshot['annotations'];lectures:Snapshot['lectures'];files:Snapshot['files'];academic?:Academic};
export type Envelope={format:'study-notebook.aes-gcm.v1';iv:string;data:string};
export const emptyOverlay=():Overlay=>({revision:0,completed:{},tasks:{},grades:{},practice:{},annotations:{},lectures:{},files:{}});
export function base64(bytes:Uint8Array){let text='';for(const b of bytes)text+=String.fromCharCode(b);return btoa(text);}
export function unbase64(text:string){return Uint8Array.from(atob(text.replace(/-/g,'+').replace(/_/g,'/')),c=>c.charCodeAt(0));}
export async function importKey(raw:string){const bytes=unbase64(raw);if(bytes.length!==32)throw new Error('This is not a notebook unlock key.');return crypto.subtle.importKey('raw',bytes,'AES-GCM',false,['encrypt','decrypt']);}
export async function encrypt(value:unknown,key:CryptoKey):Promise<Envelope>{const iv=crypto.getRandomValues(new Uint8Array(12));const data=await crypto.subtle.encrypt({name:'AES-GCM',iv,additionalData:new TextEncoder().encode('study-notebook:v1')},key,new TextEncoder().encode(JSON.stringify(value)));return {format:'study-notebook.aes-gcm.v1',iv:base64(iv),data:base64(new Uint8Array(data))};}
export async function decrypt<T>(v:Envelope,key:CryptoKey):Promise<T>{if(v?.format!=='study-notebook.aes-gcm.v1'||typeof v.iv!=='string'||typeof v.data!=='string'||unbase64(v.iv).length!==12)throw new Error('The notebook file has an unsupported format.');try{const raw=await crypto.subtle.decrypt({name:'AES-GCM',iv:unbase64(v.iv),additionalData:new TextEncoder().encode('study-notebook:v1')},key,unbase64(v.data));return JSON.parse(new TextDecoder().decode(raw));}catch{throw new Error('This key could not unlock the notebook, or the file is damaged.');}}
function record(v:unknown):v is Record<string,any>{return !!v&&typeof v==='object'&&!Array.isArray(v)&&(Object.getPrototypeOf(v)===Object.prototype||Object.getPrototypeOf(v)===null);}
function textField(v:unknown,max=10000){return typeof v==='string'&&v.length<=max;}
function timestamp(v:unknown){return typeof v==='string'&&!Number.isNaN(Date.parse(v));}
function safeId(v:unknown){return typeof v==='string'&&/^[\w-]{1,160}$/.test(v)&&!['__proto__','prototype','constructor'].includes(v);}
function mapField(v:unknown){return record(v)&&Object.keys(v).every(safeId);}
const attachmentTypes=['application/pdf','image/png','image/jpeg','image/webp','text/plain','text/markdown','application/vnd.openxmlformats-officedocument.presentationml.presentation'];
export function validateSnapshot(s:Snapshot){
  if(!record(s)||s.schemaVersion!==2||!safeId(s.notebookId)||!safeId(s.snapshotId)||!timestamp(s.publishedAt)||!record(s.academic)||!mapField(s.lectures)||!mapField(s.annotations)||!mapField(s.files))throw new Error('The notebook snapshot is incomplete.');
  const a=s.academic;
  if(!Array.isArray(a.courses)||!a.courses.length||!Array.isArray(a.assessments)||!Array.isArray(a.excluded)||!Array.isArray(a.finals)||!Array.isArray(a.series)||!validDate(a.reviewedOn)||!textField(a.sourceStatus))throw new Error('The course information is incomplete.');
  const courseIds=new Set<string>();
  for(const c of a.courses){if(!record(c)||!safeId(c.id)||courseIds.has(c.id)||!textField(c.code,100)||!(c.name===null||textField(c.name,500))||!textField(c.color,100)||!Array.isArray(c.gradeCategories)||!Array.isArray(c.gradeCaveats)||c.gradeCaveats.some(x=>!textField(x))||(c.source!==undefined&&!textField(c.source)))throw new Error('Invalid course information.');if((c.status!==undefined&&!['active','dropped'].includes(c.status))||(c.droppedOn!==undefined&&!validDate(c.droppedOn)))throw new Error('Invalid course registration status.');courseIds.add(c.id);const cats=new Set<string>();for(const cat of c.gradeCategories){if(!record(cat)||!safeId(cat.id)||cats.has(cat.id)||!textField(cat.label,500)||typeof cat.weight!=='number'||!Number.isFinite(cat.weight)||cat.weight<0||cat.weight>100)throw new Error('Invalid grading category.');cats.add(cat.id);for(const k of ['dropLowest','totalItems','countBest'] as const)if(cat[k]!==undefined&&(!Number.isInteger(cat[k])||cat[k]!<0))throw new Error('Invalid grading rule.');if(cat.countBest&&(!cat.totalItems||cat.countBest>cat.totalItems||typeof cat.countedItemWeight!=='number'||!Number.isFinite(cat.countedItemWeight)||cat.countedItemWeight<=0))throw new Error('Invalid best-score grading rule.');}}
  for(const items of [a.assessments,a.excluded,a.finals]){const ids=new Set<string>();for(const item of items){if(!record(item)||!safeId(item.id)||ids.has(item.id)||!courseIds.has(item.course)||!textField(item.title,1000)||!(item.date===null||validDate(item.date))||!(item.time===null||textField(item.time,30))||!textField(item.status,1000)||!textField(item.source))throw new Error('Invalid assessment information.');ids.add(item.id);}}
  for(const series of a.series){if(!record(series)||!safeId(series.course)||!textField(series.location,1000)||!/^\d{2}:\d{2}$/.test(series.start_time)||!/^\d{2}:\d{2}$/.test(series.end_time)||!Array.isArray(series.periods))throw new Error('Invalid class schedule.');for(const period of series.periods)if(!record(period)||!validDate(period.start)||!validDate(period.end_inclusive)||period.start>period.end_inclusive||!Array.isArray(period.days)||period.days.some(d=>!['SU','MO','TU','WE','TH','FR','SA'].includes(d)))throw new Error('Invalid class recurrence.');}
  validateState(s.state,a);
  for(const l of Object.values(s.lectures)){if(!record(l)||!Array.isArray(l.versions)||!l.versions.length)throw new Error('A lecture has no source versions.');const versions=new Set<number>();let identity:string|undefined;for(const v of l.versions){if(!record(v)||!Number.isSafeInteger(v.version)||v.version<1||versions.has(v.version)||!timestamp(v.updatedAt))throw new Error('Invalid lecture source revision.');versions.add(v.version);validateLecture(v.lecture,a);const currentIdentity=JSON.stringify([v.lecture.course,v.lecture.date,v.lecture.meetingId||null]);if(identity!==undefined&&identity!==currentIdentity)throw new Error('A lecture history contains different recordings.');identity=currentIdentity;}}
  for(const [id,n] of Object.entries(s.annotations))if(!s.lectures[id]||!record(n)||!textField(n.text,200000)||!Number.isSafeInteger(n.revision)||n.revision<0)throw new Error('Invalid personal annotation.');
  for(const f of Object.values(s.files)){if(!record(f)||!s.lectures[f.noteId]||!textField(f.name,1000)||!f.name||!attachmentTypes.includes(f.type)||!textField(f.data,20000000)||!/^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$/.test(f.data)||unbase64(f.data).length>15000000)throw new Error('Invalid notebook attachment.');}
}
export function validateLecture(p:Lecture,a:Academic){
  if(!record(p)||!a.courses.some(c=>c.id===p.course))throw new Error('Select a known course.');
  if(!validDate(p.date)||p.date<'2026-09-02'||p.date>'2026-12-31')throw new Error('Enter a valid Fall 2026 lecture date.');
  if(!textField(p.title,200)||!p.title.trim()||!textField(p.transcript,350000)||!p.transcript.trim())throw new Error('Enter a title and source transcript (up to 350,000 characters).');
  if(!['complete','partial','unknown'].includes(p.captureStatus))throw new Error('Choose the recording coverage.');
  for(const k of ['meetingId','sourceUrl','sourceModifiedAt','quickNotes','detailedNotes'] as const)if(p[k]!==undefined&&!textField(p[k],1000000))throw new Error('Invalid lecture field: '+k);
  if(p.meetingId&&!/^[\w-]{1,100}$/.test(p.meetingId))throw new Error('Invalid recording identity.');
  if(p.sourceUrl&&!/^https:\/\//.test(p.sourceUrl))throw new Error('Source links must use HTTPS.');
  if(p.sourceModifiedAt&&!timestamp(p.sourceModifiedAt))throw new Error('Invalid source timestamp.');
  if(p.questions!==undefined&&(!Array.isArray(p.questions)||p.questions.length>100||p.questions.some(q=>!record(q)||!textField(q.question,20000)||!textField(q.answer,50000)||(q.source!==undefined&&!textField(q.source,10000)))))throw new Error('Invalid practice questions.');
  if(p.uncertainties!==undefined&&(!Array.isArray(p.uncertainties)||p.uncertainties.length>1000||p.uncertainties.some(x=>!textField(x,20000))))throw new Error('Invalid review flags.');
  if(p.figures!==undefined&&(!Array.isArray(p.figures)||p.figures.length>100||p.figures.some(f=>!record(f)||!textField(f.title,500)||!textField(f.description,100000))))throw new Error('Invalid lecture figure descriptions.');
}
export function validDate(v:string){return typeof v==='string'&&/^\d{4}-\d{2}-\d{2}$/.test(v)&&!Number.isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;}
export function validateState(s:DeskState,a:Academic){if(!s||!Array.isArray(s.completed)||!Array.isArray(s.tasks)||!Array.isArray(s.grades)||!s.practice||typeof s.practice!=='object'||JSON.stringify(s).length>200000)throw new Error('Invalid study data.');if(s.completed.some(id=>!a.assessments.some(x=>x.id===id)))throw new Error('Unknown assessment completion.');const taskIds=new Set();for(const t of s.tasks){if(!a.courses.some(c=>c.id===t.course)||typeof t.id!=='string'||taskIds.has(t.id)||typeof t.title!=='string'||t.title.length>300||typeof t.reason!=='string'||t.reason.length>6000||typeof t.done!=='boolean'||!validDate(t.date))throw new Error('Invalid study task.');taskIds.add(t.id);}const gradeIds=new Set();for(const g of s.grades){const cat=a.courses.find(c=>c.id===g.course)?.gradeCategories.find(c=>c.id===g.category);const id=g.course+':'+g.category;if(!cat||gradeIds.has(id)||typeof g.feedback!=='string'||g.feedback.length>5000)throw new Error('Invalid grade record.');gradeIds.add(id);const scores=cat.countBest?(g.scores||[]):[g.score];if(cat.countBest&&scores.length!==cat.totalItems)throw new Error('Keep ungraded quizzes blank.');if(scores.some(x=>x!==null&&(typeof x!=='number'||!Number.isFinite(x)||x<0||x>100)))throw new Error('Grades must be 0–100; ungraded marks stay blank.');}for(const v of Object.values(s.practice))if(!v||!Number.isInteger(v.attempts)||!Number.isInteger(v.correct)||v.correct<0||v.attempts<v.correct)throw new Error('Invalid practice result.');}
export function canonicalLecture(p:Lecture):Lecture{return Object.fromEntries(['meetingId','course','date','title','transcript','quickNotes','detailedNotes','questions','sourceUrl','sourceModifiedAt','captureStatus','uncertainties','figures'].filter(k=>Object.hasOwn(p,k)).map(k=>[k,p[k as keyof Lecture]])) as Lecture;}
export async function hash(s:string){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))].map(x=>x.toString(16).padStart(2,'0')).join('');}
export function lectureStatus(p:Lecture){return p.captureStatus==='partial'?'Partial recording':!p.detailedNotes?'Awaiting notes':p.captureStatus==='unknown'||p.uncertainties?.length||!/#source-L\d+/.test(p.detailedNotes)?'Needs review':'Ready';}
export async function addLecture(snapshot:Snapshot,overlay:Overlay,raw:Lecture){const p=canonicalLecture(raw);validateLecture(p,overlay.academic||snapshot.academic);const id=p.meetingId?'wispr-'+p.meetingId:'manual-'+await hash(p.course+':'+p.date+':'+p.title);const all=mergeLectures(snapshot.lectures,overlay.lectures);const versions=all[id]?.versions||[];const old=versions.at(-1)?.lecture;if(old&&(old.course!==p.course||old.date!==p.date))throw new Error('This recording already belongs to another course or date.');if(old&&await hash(JSON.stringify(old))===await hash(JSON.stringify(p)))return {id,version:versions.at(-1)!.version,unchanged:true};if(old?.sourceModifiedAt&&(!p.sourceModifiedAt||Date.parse(p.sourceModifiedAt)<Date.parse(old.sourceModifiedAt)))throw new Error('This transcript is older than the saved source. The newer source is preserved.');const version=(versions.at(-1)?.version||0)+1;overlay.lectures[id]={versions:[...versions,{version,updatedAt:new Date().toISOString(),lecture:p}]};return {id,version,unchanged:false};}
export function mergeLectures(base:Snapshot['lectures'],local:Overlay['lectures']){const result=structuredClone(base);for(const [id,l] of Object.entries(local)){const remote=result[id];if(!remote){result[id]=l;continue;}const unique=[...remote.versions];for(const v of l.versions)if(!unique.some(x=>JSON.stringify(x.lecture)===JSON.stringify(v.lecture)))unique.push(v);unique.sort((a,b)=>Date.parse(a.lecture.sourceModifiedAt||a.updatedAt)-Date.parse(b.lecture.sourceModifiedAt||b.updatedAt));result[id]={versions:unique.map((v,i)=>({...v,version:i+1}))};}return result;}
function applyMap<T>(base:T[],patch:Record<string,T|null>,key:(v:T)=>string){const values=new Map(base.map(v=>[key(v),v]));for(const [k,v] of Object.entries(patch))if(v===null)values.delete(k);else values.set(k,v);return [...values.values()];}
export function mergedState(base:DeskState,o:Overlay):DeskState{const completed=new Set(base.completed);for(const [id,done] of Object.entries(o.completed))if(done)completed.add(id);else completed.delete(id);return {...base,completed:[...completed],tasks:applyMap(base.tasks,o.tasks,x=>x.id),grades:applyMap(base.grades,o.grades,x=>x.course+':'+x.category),practice:{...base.practice,...o.practice},lastRequest:o.lastRequest??base.lastRequest};}
export function patchState(base:DeskState,next:DeskState,o:Overlay){const before=new Set(base.completed),after=new Set(next.completed);for(const id of new Set([...before,...after]))if(before.has(id)!==after.has(id))o.completed[id]=after.has(id);for(const [b,n,dest,key] of [[base.tasks,next.tasks,o.tasks,(x:any)=>x.id],[base.grades,next.grades,o.grades,(x:any)=>x.course+':'+x.category]] as const){const prev=new Map(b.map((v:any)=>[key(v),v]));const current=new Map(n.map((v:any)=>[key(v),v]));for(const id of new Set([...prev.keys(),...current.keys()]))if(JSON.stringify(prev.get(id))!==JSON.stringify(current.get(id)))(dest as Record<string,any>)[id]=current.get(id)||null;}for(const [k,v] of Object.entries(next.practice))if(JSON.stringify(base.practice[k])!==JSON.stringify(v))o.practice[k]=v;if(next.lastRequest!==base.lastRequest)o.lastRequest=next.lastRequest;}
