import {activeAcademic} from './domain';
import type {DashboardData, NoteMeta, NoteDetail, Lecture} from './domain';
import {addLecture,base64,decrypt,emptyOverlay,encrypt,hash,importKey,lectureStatus,mergeLectures,mergedState,patchState,unbase64,validateSnapshot,validateState,type Envelope,type Overlay,type Snapshot} from './notebook-model';

let snapshot:Snapshot, key:CryptoKey;
const namespace = new URL(import.meta.env.BASE_URL,location.href).pathname;
const dbPromise=new Promise<IDBDatabase>((resolve,reject)=>{const req=indexedDB.open('semester-notebook',1);req.onupgradeneeded=()=>req.result.createObjectStore('private');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(new Error('Browser storage is unavailable. Enable storage to use this notebook.'));});
async function read<T>(id:string):Promise<T|undefined>{const db=await dbPromise;return new Promise((resolve,reject)=>{const tx=db.transaction('private');const req=tx.objectStore('private').get(namespace+id);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
async function write(id:string,value:unknown){const db=await dbPromise;await new Promise<void>((resolve,reject)=>{const tx=db.transaction('private','readwrite');if(value===undefined)tx.objectStore('private').delete(namespace+id);else tx.objectStore('private').put(value,namespace+id);tx.oncomplete=()=>resolve();tx.onerror=()=>reject(new Error('Your edit could not be saved. Browser storage may be full. Export your work before closing.'));tx.onabort=()=>reject(new Error('Saving was interrupted. Your edit has not been saved.'));});}
async function published(){const response=await fetch(new URL('notebook.enc.json',new URL(import.meta.env.BASE_URL,location.href)),{cache:'no-store',credentials:'omit'});if(!response.ok)throw new Error('The published notebook could not be loaded. Check your connection and try again.');return response.json() as Promise<Envelope>;}
async function overlay(){const encrypted=await read<Envelope>('edits:'+snapshot.notebookId);return encrypted?decrypt<Overlay>(encrypted,key):emptyOverlay();}
async function persist(o:Overlay){await write('edits:'+snapshot.notebookId,await encrypt(o,key));}
async function exclusive<T>(fn:()=>Promise<T>):Promise<T>{if(!navigator.locks)throw new Error('Saving requires a current browser with Web Locks support. You can still read and export this notebook.');return navigator.locks.request('notebook:'+namespace,fn);}
async function change<T>(fn:(o:Overlay)=>Promise<T>|T){return exclusive(async()=>{const o=await overlay();const result=await fn(o);validateSnapshot(current(o));await persist(o);return result;});}
export async function unlockNotebook(file:File,remember:boolean){return unlockWithText(await file.text(),remember);}
export async function unlockWithText(text:string,remember:boolean){const k=text.trim().startsWith('{')?JSON.parse(text):{format:'study-notebook.key.v1',key:text.trim()};if(k?.format!=='study-notebook.key.v1'||typeof k.key!=='string')throw new Error('Choose the notebook unlock-key.json file.');const candidate=await importKey(k.key);const s=await decrypt<Snapshot>(await published(),candidate);validateSnapshot(s);snapshot=s;key=candidate;await overlay();await write('key',remember?key:undefined);return dashboard();}
export async function resumeNotebook(){const remembered=await read<CryptoKey>('key');if(!remembered)return null;const s=await decrypt<Snapshot>(await published(),remembered);validateSnapshot(s);snapshot=s;key=remembered;return dashboard();}
export async function refreshPublished(){const s=await decrypt<Snapshot>(await published(),key);validateSnapshot(s);if(s.notebookId!==snapshot.notebookId)throw new Error('This update belongs to a different notebook.');const old=snapshot;snapshot=s;try{return await dashboard();}catch(e){snapshot=old;throw e;}}
export function publishedOn(){return snapshot.publishedAt;}
export async function lockNotebook(){await write('key',undefined);location.reload();}
function current(o:Overlay):Snapshot{return {...snapshot,academic:o.academic||snapshot.academic,state:mergedState(snapshot.state,o),lectures:mergeLectures(snapshot.lectures,o.lectures),annotations:{...snapshot.annotations,...o.annotations},files:{...snapshot.files,...o.files}};}
async function meta(id:string,v:Snapshot['lectures'][string]['versions'][number]):Promise<NoteMeta>{const p=v.lecture;return {id,course:p.course,date:p.date,title:p.title,status:lectureStatus(p),version:v.version,updatedAt:v.updatedAt,sourceHash:await hash(JSON.stringify(p)),excerpt:(p.quickNotes||p.transcript).slice(0,220)};}
async function dashboard():Promise<DashboardData>{const o=await overlay();const s=current(o);const notes=await Promise.all(Object.entries(s.lectures).map(([id,l])=>meta(id,l.versions.at(-1)!)));const academic=activeAcademic(s.academic);const active=new Set(academic.courses.map(c=>c.id));return {academic,state:s.state,stateRevision:o.revision,notes:notes.filter(n=>active.has(n.course)).sort((a,b)=>b.date.localeCompare(a.date)),name:'Adam',local:true};}
function revision(expected:unknown,o:Overlay){if(expected!==o.revision)throw new Error('Another tab changed your study data. Reload this page before saving again.');}
export async function notebookApi<T>(url:string,options?:RequestInit):Promise<T>{if(!key||!snapshot)throw new Error('Unlock your notebook first.');const path=new URL(url,location.origin);const method=options?.method||'GET';const json=()=>JSON.parse(String(options?.body||'{}'));
  let result:unknown;
  if(path.pathname==='/api/data'&&method==='GET')result=await dashboard();
  else if(path.pathname==='/api/data'&&method==='PUT'){const body=json();result=await change(o=>{revision(body.revision,o);validateState(body.state,o.academic||snapshot.academic);patchState(mergedState(snapshot.state,o),body.state,o);return {revision:++o.revision};});}
  else if(path.pathname==='/api/import'&&method==='POST'){const body=json() as Lecture;result=await change(async o=>{const r=await addLecture(snapshot,o,body);if(!r.unchanged)o.revision++;return r;});}
  else if(path.pathname.startsWith('/api/notes/')){const id=decodeURIComponent(path.pathname.slice('/api/notes/'.length));
    if(method==='GET'){const o=await overlay();const s=current(o);const versions=s.lectures[id]?.versions;if(!versions)throw new Error('Lecture not found.');const selected=path.searchParams.get('version');const v=selected?versions.find(v=>v.version===Number(selected)):versions.at(-1);if(!v)throw new Error('Source revision not found.');const annotation=s.annotations[id]||{text:'',revision:0};result={...await meta(id,versions.at(-1)!),...v.lecture,viewingVersion:v.version,annotation:annotation.text,annotationRevision:annotation.revision,versions:versions.map(({version,updatedAt})=>({version,updatedAt})),files:Object.entries(s.files).filter(([,f])=>f.noteId===id).map(([id,f])=>({id,name:f.name,type:f.type}))} satisfies NoteDetail & {viewingVersion:number};}
    else if(method==='PUT'){const body=json();result=await change(o=>{const s=current(o);if(!s.lectures[id])throw new Error('Lecture not found.');const old=s.annotations[id]||{text:'',revision:0};if(body.revision!==old.revision)throw new Error('Another tab changed this annotation. Download your unsaved edits, then reload the lecture to reconcile them.');if(typeof body.annotation!=='string'||body.annotation.length>200000)throw new Error('Personal notes must be under 200,000 characters.');o.annotations[id]={text:body.annotation,revision:old.revision+1};return {revision:old.revision+1};});}
  }
  else if(path.pathname==='/api/files/upload'&&method==='POST'){const form=options?.body;if(!(form instanceof FormData))throw new Error('Choose an attachment.');const f=form.get('file'),noteId=form.get('noteId');if(!(f instanceof File)||typeof noteId!=='string')throw new Error('Choose an attachment and a lecture.');if(f.size>15000000)throw new Error('Attachments must be under 15 MB.');if(!['application/pdf','image/png','image/jpeg','image/webp','text/plain','text/markdown','application/vnd.openxmlformats-officedocument.presentationml.presentation'].includes(f.type))throw new Error('Use a PDF, PNG, JPEG, WebP, text, or PowerPoint file.');const data=base64(new Uint8Array(await f.arrayBuffer()));result=await change(o=>{if(!current(o).lectures[noteId])throw new Error('Lecture not found.');const id=crypto.randomUUID();o.files[id]={noteId,name:f.name,type:f.type,data};return {id};});}
  else if(path.pathname==='/api/export'&&method==='GET')result=current(await overlay());
  else if(path.pathname==='/api/restore'&&method==='POST'){const backup=json() as Snapshot&{expectedRevision:number};validateSnapshot(backup);if(backup.notebookId!==snapshot.notebookId)throw new Error('This backup belongs to a different notebook.');result=await change(async o=>{revision(backup.expectedRevision,o);const before=current(o);await write('checkpoint:'+snapshot.notebookId,await encrypt(before,key));validateState(backup.state,before.academic);patchState(before.state,backup.state,o);o.lectures=mergeLectures(backup.lectures,o.lectures);o.annotations={...backup.annotations,...before.annotations};o.files={...backup.files,...before.files};o.revision++;return {imported:Object.keys(backup.lectures).length};});}
  else if(path.pathname==='/api/checkpoint'&&method==='GET'){const v=await read<Envelope>('checkpoint:'+snapshot.notebookId);if(!v)throw new Error('There is no restore checkpoint on this device yet.');result=await decrypt<Snapshot>(v,key);}
  else throw new Error('This action is not available in the static notebook.');
  return result as T;
}
export async function downloadAttachment(id:string){const f=current(await overlay()).files[id];if(!f)throw new Error('Attachment not found.');const bytes=unbase64(f.data);const url=URL.createObjectURL(new Blob([bytes],{type:f.type}));const a=document.createElement('a');a.href=url;a.download=f.name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
